language: python
python:
  - "3.5"
sudo: required
# command to install dependencies
install: 
  - "pip install flake8"
  - "pip install -r requirements.txt"
  - sudo mkdir /var/log/hb
  - sudo mkdir -p /config/logs/hb
  - sudo chown $USER /config/logs/hb
  - sudo chown $USER /config
  - cp html_browser_site/local_settings_docker.py html_browser_site/local_settings.py
  - cp html_browser_site/local_settings_docker.json /config/local_settings.json

before_script:
  - "flake8 ."
# command to run tests
script: 
  - python manage.py test

