dist: focal
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

sudo: required

# command to install dependencies
install: 
  - "pip install flake8 pylint==2.12.0 pylint-django django-stubs==1.9.0 mypy"
  - "pip install -r requirements.txt"
  - mkdir log
  - cp cygwin.env .env

before_script:
  - "flake8 ."
  - "./pylint.sh ./html_browser"
  - "mypy html_browser"
# command to run tests
script: 
# run tests without a url prefix
  - python manage.py test
# run again with a url prefix
  - echo '{"URL_PREFIX":"hb/"}' > local_settings.json
  - python manage.py test

