dist: xenial
language: python
python:
  - "3.6"
  - "3.6.8" # docker image uses 3.6.8
  - "3.7"
  - "3.8"

sudo: required

# command to install dependencies
install: 
  - "pip install flake8"
  - "pip install -r requirements.txt"
  - sudo mkdir /var/log/hb
  - sudo mkdir -p /config/logs/hb
  - sudo chown $USER /config/logs/hb
  - cp html_browser/local_settings/local_settings_cygwin.py html_browser/local_settings/local_settings.py

before_script:
  - "flake8 ."
# command to run tests
script: 
  - python manage.py test

