dist: focal
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

sudo: required

# command to install dependencies
install: 
  - "pip install flake8 pylint pylint-django"
  - "pip install -r requirements.txt"
  - mkdir log
  - cp cygwin.env .env

before_script:
  - "flake8 ."
  - "./pylint.sh ./html_browser"
# command to run tests
script: 
  - python manage.py test

