dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9.5"

sudo: required

# command to install dependencies
install: 
  - "pip install flake8"
  - "pip install -r requirements.txt"
  - sudo mkdir /var/log/hb
  - sudo mkdir -p /config/logs/hb
  - sudo chown $USER /config/logs/hb
  - cp html_browser/cygwin.env html_browser/.env

before_script:
  - "flake8 ."
# command to run tests
script: 
  - python manage.py test

