dist: xenial
language: python
python:
  - "3.5"
services:
  - docker

sudo: required

before_install :
  - docker build -t HTML_BROWSER --pull docker
  - sudo mkdir /config
  - docker run -d -p 8000:8000 -v /config:/config -v /:/data1 -e APP_UID=1000 -e APP_GID=1000 --name HTML_BROWSER HTML_BROWSER
  - docker ps -a
  - docker exec -it HTML_BROWSER /bin/bash -c "cd /hb; python manage.py test"
# command to install dependencies
install: 
  - "pip install flake8"
  - "pip install -r requirements.txt"
  - sudo mkdir /var/log/hb
  - sudo mkdir -p /config/logs/hb
  - sudo chown $USER /config/logs/hb
  - sudo chown $USER /config
  - cp html_browser_site/local_settings_docker.py html_browser_site/local_settings.py
  - cp html_browser_site/local_settings_docker.json /config/local_settings.json

before_script:
  - "flake8 ."
# command to run tests
script: 
  - python manage.py test

