dist: xenial
language: python
python:
  - "3.6.8"
services:
  - docker

sudo: required

before_install :
  - docker build -t html_browser --pull .
  - sudo mkdir /config
  - sudo chown $USER /config
  - docker run -d -p 8000:80 -v /config:/config -v /:/data1 -e USERID=1010 -e GROUPID=1010 -e USERNAME=hb_user -e GROUPNAME=hb_group -e HOMEDIR=/hb --name html_browser html_browser
  - docker ps -a
  - docker exec -it html_browser /bin/bash -c "cd /hb; python manage.py test"
# command to install dependencies
install: 
  - "pip install flake8"
  - "pip install -r requirements.txt"
  - sudo mkdir /var/log/hb
  - sudo mkdir -p /config/logs/hb
  - sudo chown $USER /config/logs/hb
  - cp html_browser/local_settings/local_settings_docker_sqlite.py html_browser/local_settings/local_settings.py
  - cp html_browser/local_settings/local_settings_docker_sqlite.json /config/local_settings.json

before_script:
  - "flake8 ."
# command to run tests
script: 
  - python manage.py test

