dist: xenial
language: python
python:
  - "3.6.8"
services:
  - docker

sudo: required

# command to install dependencies
install: 
  - "pip install flake8"
  - "pip install -r requirements.txt"
  - sudo mkdir /var/log/hb
  - sudo mkdir -p /config/logs/hb
  - sudo chown $USER /config/logs/hb
  - cp html_browser/local_settings/local_settings_docker_sqlite.py html_browser/local_settings/local_settings.py
  - cp html_browser/local_settings/local_settings_docker_sqlite.json html_browser/local_settings.json

before_script:
  - "flake8 ."
# command to run tests
script: 
  - python manage.py test

