from hb_mysql:latest

env PYTHONBUFFERED 1

workdir /hb

run apk add --no-cache mariadb mariadb-client openrc && \
    apk add --no-cache --virtual .builddeps mariadb-dev gcc musl-dev python3-dev && \
    pip install --no-cache mysqlclient==1.4.2 && \
    apk del .builddeps && \
    find /usr/local \
        \( -type d -a -name test -o -name tests \) \
        -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
        -exec rm -rf '{}' + \
    && runDeps="$( \
        scanelf --needed --nobanner --recursive /usr/local \
                | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
                | sort -u \
                | xargs -r apk info --installed \
                | sort -u \
    )" \
    && apk add --virtual .rundeps $runDeps 

copy html_browser/local_settings/local_settings_docker_mysql.py /hb/html_browser/local_settings/local_settings.py
copy html_browser/local_settings/local_settings_docker_mysql.json /hb/html_browser/local_settings/local_settings.json

copy docker/init_mysql.sh /init_db.sh

ENV DB_USER="db_user"
ENV DB_PASS="db_pass"
ENV DB_ROOT_PASS="db_root_pass"
env DB_NAME="hb_db"

ENTRYPOINT ["/entrypoint.sh"]
