# Generated by Django 3.2.10 on 2021-12-27 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesToDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=250)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('local_path', models.CharField(max_length=100, unique=True)),
                ('view_option', models.CharField(choices=[('P', 'View authorization set by user and group permissions'), ('E', 'Viewable by any registered user'), ('A', 'Viewable by anonymous users')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.SmallIntegerField(choices=[(1, 'Read Only'), (2, 'Read/Write'), (3, 'Read/Write/Delete')], default=1)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='html_browser.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('folder', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.SmallIntegerField(choices=[(1, 'Read Only'), (2, 'Read/Write'), (3, 'Read/Write/Delete')], default=1)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='html_browser.folder')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'unique_together': {('folder', 'group')},
            },
        ),
    ]
