# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_browser', '0002_folder_grouppermission_userpermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppermission',
            old_name='permission',
            new_name='tempOldpermission',
        ),
        migrations.RenameField(
            model_name='userpermission',
            old_name='permission',
            new_name='tempOldpermission',
        ),
    ]
