# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 21:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_browser', '0003_auto_20161022_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='permission',
            field=models.SmallIntegerField(choices=[(1, b'Read Only'), (2, b'Read/Write'), (3, b'Read/Write/Delete')], default=1),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.SmallIntegerField(choices=[(1, b'Read Only'), (2, b'Read/Write'), (3, b'Read/Write/Delete')], default=1),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='tempOldpermission',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='tempOldpermission',
            field=models.CharField(max_length=1),
        ),
    ]
