# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 21:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_browser', '0005_custom_convert_perm_20161022_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppermission',
            name='tempOldpermission',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='tempOldpermission',
        ),
    ]
