# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('html_browser', '0007_filestodelete'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together=set([('folder', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together=set([('folder', 'user')]),
        ),
    ]
