# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_browser', '0007_filestodelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='viewOption',
            field=models.CharField(choices=[('P', 'View authorization set by user and group permissions'),
                                            ('E', 'Viewable by any registered user'), ('A', 'Viewable by anonymous users')],
                                   default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='permission',
            field=models.SmallIntegerField(choices=[(1, 'Read Only'), (2, 'Read/Write'), (3, 'Read/Write/Delete')], default=1),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.SmallIntegerField(choices=[(1, 'Read Only'), (2, 'Read/Write'), (3, 'Read/Write/Delete')], default=1),
        ),
    ]
