# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_browser', '0008_auto_20161105_1011'),
        ('html_browser', '0008_auto_20161022_2331'),
    ]

    operations = [
    ]
