# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 21:31


from django.db import migrations
from html_browser_site import settings
import os


def linkFolder(folder):
    if not os.path.isdir(settings.FOLDER_LINK_DIR):
        os.makedirs(settings.FOLDER_LINK_DIR)

    link = os.path.join(settings.FOLDER_LINK_DIR, folder.name)
    os.symlink(folder.localPath, link)


class Migration(migrations.Migration):

    def postMigrate(apps, schema_editor):
        folderModel = apps.get_model('html_browser', 'Folder')
        for folder in folderModel.objects.all():
            linkFolder(folder)

    dependencies = [
        ('html_browser', '0009_merge_20161110_0128'),
    ]

    operations = [
        migrations.RunPython(postMigrate),
    ]
