#pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 21:31


from django.db import migrations


def convert_perm(perm_model):
    for perm in perm_model.objects.all():
        perm.p2 = int(perm.permission)
        perm.save()


class Migration(migrations.Migration):

    def postMigrate(apps, schema_editor):
        user_perm_model = apps.get_model('html_browser', 'UserPermission')
        convert_perm(user_perm_model)

        group_perm_model = apps.get_model('html_browser', 'GroupPermission')
        convert_perm(group_perm_model)

    dependencies = [
        ('html_browser', '0011_auto_20170404_2102'),
    ]

    operations = [
        migrations.RunPython(postMigrate),
    ]
