# Generated by Django 3.0 on 2019-12-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_browser', '0014_auto_20170404_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filestodelete',
            old_name='filePath',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='localPath',
            new_name='local_path',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='viewOption',
            new_name='view_option',
        ),
    ]
