from django.conf.urls import patterns, url

urlpatterns = [
    url(r'^$', 'html_browser.views.index'),
    url(r'^hb/$', 'html_browser.views.index'),
    url(r'content/.*', 'html_browser.views.content'),
    url(r'download_zip/.*', 'html_browser.views.downloadZip'),
    url(r'download/.*', 'html_browser.views.download'),
    url(r'hbLogin/.*', 'html_browser.views.hbLogin'),
    url(r'hbLogout/.*', 'html_browser.views.hbLogout'),
    url(r'hbAdmin/.*', 'html_browser.views.hbAdmin'),
    url(r'userAdmin/.*', 'html_browser.views.userAdmin'),
    url(r'userAdminAction/.*', 'html_browser.views.userAdminAction'),
    url(r'editUser/.*', 'html_browser.views.editUser'),
    url(r'addUser/.*', 'html_browser.views.addUser'),
    url(r'editGroup/.*', 'html_browser.views.editGroup'),
    url(r'folderAdmin/.*', 'html_browser.views.folderAdmin'),
    url(r'folderAdminAction/.*', 'html_browser.views.folderAdminAction'),
    url(r'editFolder/.*', 'html_browser.views.editFolder'),
    url(r'addFolder/.*', 'html_browser.views.addFolder'),
    url(r'groupAdmin/.*', 'html_browser.views.groupAdmin'),
    url(r'groupAdminAction/.*', 'html_browser.views.groupAdminAction'),
    url(r'hbChangePassword/.*', 'html_browser.views.hbChangePassword'),
    url(r'hbChangePasswordResult/.*', 'html_browser.views.hbChangePasswordResult'),
    url(r'upload/.*', 'html_browser.views.upload'),
    url(r'image_view/.*', 'html_browser.views.imageView'),
    url(r'thumb/', 'html_browser.views.thumb'),
    url(r'deleteImage', 'html_browser.views.deleteImage'),
    url(r'getNextImage', 'html_browser.views.getNextImage'),
    ]
